### Variables & Data Types

#### Variable Assignment

In [1]:
x = 5
x

5

#### Calculations With Variables

In [2]:
x + 2

7

In [3]:
x - 2

3

In [4]:
x * 2

10

In [5]:
x ** 2

25

#### Numpy Arrays

In [7]:
import numpy as np
from math import pi

In [8]:
my_list = [1, 2, 3, 4]
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4])

In [10]:
my_2darray = np.array([[1,2,3,4],[5,6,7,8]])
my_2darray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### Selecting NumPy Array Elements

In [11]:
# Subset
my_array[1]

2

In [12]:
# Slice
my_array[0:2]

array([1, 2])

In [15]:
# Slice 2D Array
my_2darray[1:2]

array([[5, 6, 7, 8]])

#### NumPy Array Operations

In [16]:
my_array.shape

(4,)

In [22]:
np.insert(my_array, 1, 2)

array([1, 2, 2, 3, 4])

In [20]:
np.delete(my_array,[1])

array([1, 3, 4])

In [23]:
np.mean(my_array)

2.5

In [24]:
np.median(my_array)

2.5

In [26]:
np.corrcoef(my_array)

1.0

In [27]:
np.std(my_array)

1.118033988749895

In [28]:
my_array > 2

array([False, False,  True,  True])

#### NumPy 3D Arrays

In [30]:
array_1 = [1,2,3,4]
array_2 = [5,6,7,8]
array_3 = [9,10,11,12]
my_3dArray = np.array([array_1, array_2, array_3])
my_3dArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### Initial Placeholders

In [32]:
# Create An Array Of 0's
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
# Create An Array Of 1's
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
# Create An Array With Step Values
x = np.arange(10, 25, 5)
x

array([10, 15, 20])

In [41]:
# Create An Array With Number Of Samples
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [47]:
# Create An Matrix Of One Constant
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [51]:
# Create An Identity Matrix
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [56]:
np.random.random((2,2))

array([[0.88919701, 0.66619242],
       [0.55384899, 0.82901074]])

In [58]:
np.random.randint((2,5))

array([0, 2])

In [61]:
# Convert floats to integers
integer_array = np.random.randint(0, 100, size=float_array.shape)

print("\nRandom integer array:")
print(integer_array)


Random integer array:
[[10 87]
 [ 2 88]]


#### Inspecting Your Array

In [62]:
# Shape Of Your Matrix
my_array.shape

(4,)

In [65]:
# Length Of Matrix
len(my_array)

4

In [67]:
# Number Of Dimensions
my_array.ndim

1

In [69]:
# Number Of Matrix Elements
my_array.size

4

In [72]:
# Data Type
my_array.dtype

dtype('int32')

In [73]:
# Type Conversion
my_array.astype(float)

array([1., 2., 3., 4.])

#### Arithmetic Operations On Matrix

In [78]:
my_array_1 = np.array(array_2)

In [79]:
array_1 - my_array_1

array([-4, -4, -4, -4])